root: true

ignorePatterns:
    # node_modules is implicitly always ignored
    - build

extends:
    - react-app
    - plugin:prettier/recommended

rules:
    prettier/prettier: warn
    curly: error
