/**
 * Copyright (c) 2022, RTE (http://www.rte-france.com)
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

import { INVALID_LOADFLOW_OPACITY } from '../../utils/colors';
import { FEEDER_TYPES, FeederTypes } from 'components/utils/feederType';
import { Theme } from '@mui/material';
import { DiagramMetadata, SLDMetadata } from '@powsybl/network-viewer';
import { UUID } from 'crypto';
import { EquipmentType, ExtendedEquipmentType } from '@gridsuite/commons-ui';

export const MIN_WIDTH = 150;
export const MIN_HEIGHT = 150;
export const MAX_WIDTH_VOLTAGE_LEVEL = 800;
export const MAX_HEIGHT_VOLTAGE_LEVEL = 700;
export const MAX_WIDTH_SUBSTATION = 1200;
export const MAX_HEIGHT_SUBSTATION = 700;
export const MAX_WIDTH_NETWORK_AREA_DIAGRAM = 1200;
export const MAX_HEIGHT_NETWORK_AREA_DIAGRAM = 650;

// Array of zoom levels used to determine level-of-detail rendering by applying in the network-viewer the
// corresponding css class 'nad-zoom-{level}' to the NAD's SVG.
export const NAD_ZOOM_LEVELS = [0, 2000, 3500, 6000, 9000, 12000, 15000];

export const styles = {
    divDiagram: {
        '& #nad-viewer, & #svg-container': {
            /* This is a patch to alter the divs generated by NetworkAreaDiagramViewer(), which sizes management is broken.
             * It seems to be linked to the code introduced in https://github.com/powsybl/powsybl-network-viewer/pull/161
             */
            height: '100%',
            width: '100%',
        },
        '& svg': {
            display: 'block',
            width: '100%',
            height: '100%',
        },
        overflow: 'hidden',
    },
    divNetworkAreaDiagram: (theme: Theme) => ({
        height: '100%',
        '& .nad-label-box': {
            color: theme.palette.text.primary,
            fontFamily: theme.typography.fontFamily,
        },
    }),
    divSingleLineDiagram: (theme: Theme) => ({
        '& polyline': {
            pointerEvents: 'none',
        },
        '& .sld-label, .sld-graph-label, .sld-legend': {
            fill: theme.palette.text.primary,
            fontFamily: theme.typography.fontFamily,
        },
        '& .sld-disconnector:not(.sld-fictitious), :not(.sld-breaker):not(.sld-disconnector):not(.sld-load-break-switch):not(.sld-lock .sld-disconnected):not(.sld-flash .sld-disconnected).sld-disconnected, .sld-feeder-disconnected, .sld-feeder-disconnected-connected':
            {
                stroke: theme.palette.text.primary,
            },
        '& .sld-flash, .sld-lock': {
            fill: theme.palette.text.primary,
            stroke: 'none',
        },
        '& .arrow': {
            fill: theme.palette.text.primary,
        },
    }),
    divSingleLineDiagramDevModeDisabled: (theme: Theme) => ({
        '& .sld-flash, .sld-lock': {
            display: 'none',
        },
    }),
    divDiagramReadOnly: {
        '& .sld-in .sld-label': {
            display: 'none',
        },
        '& .sld-out .sld-label': {
            display: 'none',
        },
        '& .sld-arrow-in': {
            display: 'none',
        },
        '& .sld-arrow-out': {
            display: 'none',
        },
        '& .arrow': {
            pointerEvents: 'none',
        },
    },
    divDiagramInvalid: {
        '& .sld-active-power polygon, & .sld-reactive-power polygon, & .sld-voltage polygon, & .sld-angle polygon': {
            opacity: INVALID_LOADFLOW_OPACITY,
        },
        '& .sld-active-power text, & .sld-reactive-power text, & .sld-voltage text, & .sld-angle text, & .sld-voltage.sld-bus-legend-info, & .sld-angle.sld-bus-legend-info':
            {
                fill: '#787F81',
            },
        '& .sld-overload, & .sld-vl-overvoltage, & .sld-vl-undervoltage': {
            animation: 'none !important',
        },
        '& .nad-active': {
            fill: '#787F81', // Text color of the values and arrows on lines (same color in light and dark mode)
        },
        '& .nad-bus-descr': {
            color: '#787F81',
        },
        '& .nad-branch-edges .nad-overload .nad-edge-path, & .nad-vl-nodes .nad-overvoltage, & .nad-vl-nodes .nad-undervoltage':
            {
                animation: 'none !important',
            },
    },
    paperBorders: (theme: Theme) => ({
        borderLeft: '1px solid ' + theme.palette.action.disabled,
        borderBottom: '1px solid ' + theme.palette.action.disabledBackground,
        borderRight: '1px solid ' + theme.palette.action.hover,
    }),
};

// be careful when using this method because there are treatments made on purpose
export function getEquipmentTypeFromFeederType(feederType: FeederTypes | null): {
    equipmentType: EquipmentType | null;
    equipmentSubtype?: ExtendedEquipmentType;
} | null {
    switch (feederType) {
        case FEEDER_TYPES.LINE:
            return { equipmentType: EquipmentType.LINE };
        case FEEDER_TYPES.LOAD:
            return { equipmentType: EquipmentType.LOAD };
        case FEEDER_TYPES.BATTERY:
            return { equipmentType: EquipmentType.BATTERY };
        case FEEDER_TYPES.TIE_LINE:
            return { equipmentType: EquipmentType.TIE_LINE };
        case FEEDER_TYPES.DANGLING_LINE:
            return { equipmentType: EquipmentType.DANGLING_LINE };
        case FEEDER_TYPES.GENERATOR:
            return { equipmentType: EquipmentType.GENERATOR };
        case FEEDER_TYPES.LCC_CONVERTER_STATION:
            return {
                equipmentType: EquipmentType.HVDC_LINE,
                equipmentSubtype: ExtendedEquipmentType.HVDC_LINE_LCC,
            };
        case FEEDER_TYPES.VSC_CONVERTER_STATION:
            return {
                equipmentType: EquipmentType.HVDC_LINE,
                equipmentSubtype: ExtendedEquipmentType.HVDC_LINE_VSC,
            };
        case FEEDER_TYPES.HVDC_LINE:
            return { equipmentType: EquipmentType.HVDC_LINE };
        case FEEDER_TYPES.CAPACITOR:
        case FEEDER_TYPES.INDUCTOR:
            return { equipmentType: EquipmentType.SHUNT_COMPENSATOR };
        case FEEDER_TYPES.STATIC_VAR_COMPENSATOR:
            return { equipmentType: EquipmentType.STATIC_VAR_COMPENSATOR };
        case FEEDER_TYPES.TWO_WINDINGS_TRANSFORMER:
        case FEEDER_TYPES.TWO_WINDINGS_TRANSFORMER_LEG:
        case FEEDER_TYPES.PHASE_SHIFT_TRANSFORMER:
            return { equipmentType: EquipmentType.TWO_WINDINGS_TRANSFORMER };
        case FEEDER_TYPES.THREE_WINDINGS_TRANSFORMER:
        case FEEDER_TYPES.THREE_WINDINGS_TRANSFORMER_LEG:
            return { equipmentType: EquipmentType.THREE_WINDINGS_TRANSFORMER };
        default: {
            console.log('bad feeder type ', feederType);
            return null;
        }
    }
}

export function getCommonEquipmentType(equipmentType: EquipmentType): EquipmentType | null {
    switch (equipmentType) {
        case EquipmentType.SUBSTATION:
        case EquipmentType.VOLTAGE_LEVEL:
        case EquipmentType.LINE:
        case EquipmentType.LOAD:
        case EquipmentType.BATTERY:
        case EquipmentType.TIE_LINE:
        case EquipmentType.DANGLING_LINE:
        case EquipmentType.GENERATOR:
        case EquipmentType.HVDC_LINE:
        case EquipmentType.SHUNT_COMPENSATOR:
        case EquipmentType.STATIC_VAR_COMPENSATOR:
        case EquipmentType.TWO_WINDINGS_TRANSFORMER:
        case EquipmentType.THREE_WINDINGS_TRANSFORMER:
            return equipmentType;

        case EquipmentType.VSC_CONVERTER_STATION:
        case EquipmentType.LCC_CONVERTER_STATION:
            return EquipmentType.HVDC_CONVERTER_STATION;
        default: {
            console.info('Unrecognized equipment type encountered ', equipmentType);
            return null;
        }
    }
}

export interface SldAdditionalMetadata {
    id: string;
    country: string;
    substationId?: string;
}

export interface SldSvg {
    svg: string | null;
    metadata: SLDMetadata | null;
    additionalMetadata: SldAdditionalMetadata | null;
    error?: string | null;
    svgUrl?: string | null;
}

export interface VoltageLevel {
    id?: string;
    substationId: UUID;
    country?: string;
    name?: string;
}

export interface DiagramAdditionalMetadata {
    nbVoltageLevels: number;
    scalingFactor: number;
    voltageLevels: VoltageLevel[];
}

export interface DiagramSvg {
    svg: string | null;
    metadata: DiagramMetadata | null;
    additionalMetadata: DiagramAdditionalMetadata | null;
    error?: string | null;
    svgUrl?: string | null;
}

export type Svg = DiagramSvg | SldSvg;

export const NoSvg: Svg = {
    svg: null,
    metadata: null,
    additionalMetadata: null,
    error: undefined,
    svgUrl: undefined,
};

export const equipmentsWithPopover = [
    FEEDER_TYPES.LINE,
    FEEDER_TYPES.TWO_WINDINGS_TRANSFORMER,
    FEEDER_TYPES.PHASE_SHIFT_TRANSFORMER,
];
