header:
  license:
    spdx-id: MPL-2.0
    pattern: |
      Copyright copyright \d{4}, RTE \(http:\/\/www\.rte-france\.com\)
      This Source Code Form is subject to the terms of the Mozilla Public
      License, v\. 2\.0\. If a copy of the MPL was not distributed with this
      file, You can obtain one at http:\/\/mozilla\.org\/MPL\/2\.0\/\.

  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - 'Dockerfile'
    - '**/.*'
    - '**/*.txt'
    - '**/*.json'
    - '**/*.yaml'
    - '**/*.yml'
    - '**/*.svg'
    - '**/*.css'
    - '**/*.conf'
    - '**/*.properties'

  comment: on-failure
