export const AnalysisType = {
    LOADFLOW: 'LOADFLOW',
    SECURITY: 'SECURITY',
    SENSITIVITY: 'SENSITIVITY',
    SHORTCIRCUIT: 'SHORTCIRCUIT',
    DYNAMIC_SIMULATION: 'DYNAMIC_SIMULATION',
    VOLTAGE_INIT: 'VOLTAGE_INIT',
};
