export const ComputingType = {
    LOADFLOW: 'LOADFLOW',
    SECURITY_ANALYSIS: 'SECURITY_ANALYSIS',
    SENSITIVITY_ANALYSIS: 'SENSITIVITY_ANALYSIS',
    SHORTCIRCUIT_ANALYSIS: 'SHORTCIRCUIT_ANALYSIS',
    DYNAMIC_SIMULATION: 'DYNAMIC_SIMULATION',
    VOLTAGE_INIT: 'VOLTAGE_INIT',
};
