/**
 * Copyright (c) 2022, RTE (http://www.rte-france.com)
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

import { type MuiStyles } from '@gridsuite/commons-ui';
import { INVALID_COMPUTATION_OPACITY } from 'utils/colors';

export const styles = {
    divDiagram: {
        '& #nad-viewer, & #svg-container': {
            /* This is a patch to alter the divs generated by NetworkAreaDiagramViewer(), which sizes management is broken.
             * It seems to be linked to the code introduced in https://github.com/powsybl/powsybl-network-viewer/pull/161
             */
            height: '100%',
            width: '100%',
        },
        '& svg': {
            display: 'block',
            width: '100%',
            height: '100%',
        },
        overflow: 'hidden',
    },
    divNetworkAreaDiagram: (theme) => ({
        height: '100%',
        '& .nad-label-box': {
            color: theme.palette.text.primary,
            fontFamily: theme.typography.fontFamily,
        },
        '& .nad-pst-arrow': {
            stroke: theme.palette.text.primary,
            strokeWidth: 3,
        },
    }),
    divSingleLineDiagram: (theme) => ({
        '& polyline': {
            pointerEvents: 'none',
        },
        '& .sld-label, .sld-graph-label, .sld-legend': {
            fill: theme.palette.text.primary,
            fontFamily: theme.typography.fontFamily,
        },
        '& .sld-disconnector:not(.sld-fictitious), :not(.sld-breaker):not(.sld-disconnector):not(.sld-load-break-switch):not(.sld-lock .sld-disconnected):not(.sld-flash .sld-disconnected).sld-disconnected, .sld-feeder-disconnected, .sld-feeder-disconnected-connected':
            {
                stroke: theme.palette.text.primary,
            },
        '& .sld-flash, .sld-lock': {
            stroke: 'none',
            fill: theme.palette.text.primary,
        },
        '& .arrow': {
            fill: theme.palette.text.primary,
        },
        '& .sld-pst-arrow': {
            stroke: theme.palette.text.primary,
        },
        '.legend-root': {
            display: 'inline-flex',
            gap: '8px',
            padding: '8px',
            margin: '4px',
            boxShadow: theme.shadows[2],
            borderRadius: '2px',
            backgroundColor: theme.sld.backgroundColor,
        },
        '& .legend-table td': {
            padding: '2px 16px',
        },
        '& .legend-block': {
            minWidth: '100px',
        },
        '& .legend-table': {
            width: '100%',
            borderCollapse: 'collapse',
        },
        '& .legend-title': {
            display: 'flex',
            alignItems: 'center',
            gap: '8px',
            fontWeight: '600',
            fontSize: '14px',
            margin: '0 16px 4px 16px',
        },
        '& .bus-circle': {
            width: '18px',
            height: '18px',
            borderRadius: '50%',
            display: 'inline-block',
        },
        '& .bus-circle:hover': {
            transform: 'scale(1.2)',
        },
        '& .legend-table tr': {
            borderBlock: theme.sld.border,
        },
        '& .vl-title-icon': {
            fontSize: '20px',
            lineHeight: '0px',
        },
    }),
    divSingleLineDiagramHideLockAndBolt: {
        '& .sld-flash, .sld-lock': {
            display: 'none',
        },
    },
    divDiagramReadOnly: {
        '& .sld-in .sld-label': {
            display: 'none',
        },
        '& .sld-out .sld-label': {
            display: 'none',
        },
        '& .sld-arrow-in': {
            display: 'none',
        },
        '& .sld-arrow-out': {
            display: 'none',
        },
        '& .arrow': {
            pointerEvents: 'none',
        },
    },
    divDiagramLoadflowInvalid: {
        '& .sld-active-power, & .sld-reactive-power, & .sld-current-value, & .sld-permanent-limit-percentage, & .sld-voltage, & .sld-angle, & .sld-consumption-sum, & .sld-production-sum':
            {
                opacity: INVALID_COMPUTATION_OPACITY,
            },
        '& .sld-overload, & .sld-vl-overvoltage, & .sld-vl-undervoltage': {
            animation: 'none !important',
        },
        '& .nad-active': {
            fill: '#787F81', // Text color of the values and arrows on lines (same color in light and dark mode)
        },
        '& .nad-bus-descr': {
            color: '#787F81',
        },
        '& .nad-branch-edges .nad-overload .nad-edge-path, & .nad-vl-nodes .nad-overvoltage, & .nad-vl-nodes .nad-undervoltage':
            {
                animation: 'none !important',
            },
    },
    divDiagramShortCircuitInvalid: {
        '& .sld-icc': {
            opacity: INVALID_COMPUTATION_OPACITY,
        },
    },
    hideLabels: {
        '& .nad-text-nodes': {
            display: 'none',
        },
        '& .nad-busnode-highlight': {
            filter: 'unset !important',
            transform: 'unset !important',
        },
    },
    nadEditModeCursors: {
        '& .nad-label-box, & .nad-vl-nodes .nad-busnode': {
            cursor: 'grab',
        },
    },
    paperBorders: (theme) => ({
        borderLeft: '1px solid ' + theme.palette.action.disabled,
        borderBottom: '1px solid ' + theme.palette.action.disabledBackground,
        borderRight: '1px solid ' + theme.palette.action.hover,
    }),
} as const satisfies MuiStyles;
