/**
 * Copyright (c) 2022, RTE (http://www.rte-france.com)
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

import { type MuiStyles } from '@gridsuite/commons-ui';
import { INVALID_LOADFLOW_OPACITY } from 'utils/colors';

export const styles = {
    divDiagram: {
        '& #nad-viewer, & #svg-container': {
            /* This is a patch to alter the divs generated by NetworkAreaDiagramViewer(), which sizes management is broken.
             * It seems to be linked to the code introduced in https://github.com/powsybl/powsybl-network-viewer/pull/161
             */
            height: '100%',
            width: '100%',
        },
        '& svg': {
            display: 'block',
            width: '100%',
            height: '100%',
        },
        overflow: 'hidden',
    },
    divNetworkAreaDiagram: (theme) => ({
        height: '100%',
        '& .nad-label-box': {
            color: theme.palette.text.primary,
            fontFamily: theme.typography.fontFamily,
        },
        '& .nad-pst-arrow': {
            stroke: theme.palette.text.primary,
            strokeWidth: 3,
        },
    }),
    divSingleLineDiagram: (theme) => ({
        '& polyline': {
            pointerEvents: 'none',
        },
        '& .sld-label, .sld-graph-label, .sld-legend': {
            fill: theme.palette.text.primary,
            fontFamily: theme.typography.fontFamily,
        },
        '& .sld-disconnector:not(.sld-fictitious), :not(.sld-breaker):not(.sld-disconnector):not(.sld-load-break-switch):not(.sld-lock .sld-disconnected):not(.sld-flash .sld-disconnected).sld-disconnected, .sld-feeder-disconnected, .sld-feeder-disconnected-connected':
            {
                stroke: theme.palette.text.primary,
            },
        '& .sld-flash, .sld-lock': {
            stroke: 'none',
            fill: theme.palette.text.primary,
        },
        '& .arrow': {
            fill: theme.palette.text.primary,
        },
        '& .sld-pst-arrow': {
            stroke: theme.palette.text.primary,
        },
    }),
    divSingleLineDiagramHideLockAndBolt: {
        '& .sld-flash, .sld-lock': {
            display: 'none',
        },
    },
    divDiagramReadOnly: {
        '& .sld-in .sld-label': {
            display: 'none',
        },
        '& .sld-out .sld-label': {
            display: 'none',
        },
        '& .sld-arrow-in': {
            display: 'none',
        },
        '& .sld-arrow-out': {
            display: 'none',
        },
        '& .arrow': {
            pointerEvents: 'none',
        },
    },
    divDiagramInvalid: {
        '& .sld-active-power polygon, & .sld-reactive-power polygon, & .sld-current polygon, & .sld-voltage polygon, & .sld-angle polygon':
            {
                opacity: INVALID_LOADFLOW_OPACITY,
            },
        '& .sld-active-power text, & .sld-reactive-power text, & .sld-current text, & .sld-percentage-permanent-limit text, & .sld-voltage text, & .sld-angle text, & .sld-voltage.sld-bus-legend-info, & .sld-angle.sld-bus-legend-info':
            {
                fill: '#787F81',
            },
        '& .sld-overload, & .sld-vl-overvoltage, & .sld-vl-undervoltage, & .sld-extern-cell:has(.sld-overload) .sld-current polygon':
            {
                animation: 'none !important',
            },
        '& .nad-active': {
            fill: '#787F81', // Text color of the values and arrows on lines (same color in light and dark mode)
        },
        '& .nad-bus-descr': {
            color: '#787F81',
        },
        '& .nad-branch-edges .nad-overload .nad-edge-path, & .nad-vl-nodes .nad-overvoltage, & .nad-vl-nodes .nad-undervoltage':
            {
                animation: 'none !important',
            },
    },
    hideLabels: {
        '& .nad-text-nodes': {
            display: 'none',
        },
        '& .nad-busnode-highlight': {
            filter: 'unset !important',
            transform: 'unset !important',
        },
    },
    nadEditModeCursors: {
        '& .nad-label-box, & .nad-vl-nodes .nad-busnode': {
            cursor: 'grab',
        },
    },
    paperBorders: (theme) => ({
        borderLeft: '1px solid ' + theme.palette.action.disabled,
        borderBottom: '1px solid ' + theme.palette.action.disabledBackground,
        borderRight: '1px solid ' + theme.palette.action.hover,
    }),
} as const satisfies MuiStyles;
