export const MODIFICATION_TYPE = Object.freeze({
    GROOVY_SCRIPT: 'GROOVY_SCRIPT',
    LOAD_CREATION: 'LOAD_CREATION',
    LOAD_MODIFICATION: 'LOAD_MODIFICATION',
    GENERATOR_CREATION: 'GENERATOR_CREATION',
    GENERATOR_MODIFICATION: 'GENERATOR_MODIFICATION',
    LINE_CREATION: 'LINE_CREATION',
    SUBSTATION_CREATION: 'SUBSTATION_CREATION',
    VOLTAGE_LEVEL_CREATION: 'VOLTAGE_LEVEL_CREATION',
    SHUNT_COMPENSATOR_CREATION: 'SHUNT_COMPENSATOR_CREATION',
    TWO_WINDINGS_TRANSFORMER_CREATION: 'TWO_WINDINGS_TRANSFORMER_CREATION',
    EQUIPMENT_DELETION: 'EQUIPMENT_DELETION',
    LINE_SPLIT_WITH_VOLTAGE_LEVEL: 'LINE_SPLIT_WITH_VOLTAGE_LEVEL',
    LINE_ATTACH_TO_VOLTAGE_LEVEL: 'LINE_ATTACH_TO_VOLTAGE_LEVEL',
    LINES_ATTACH_TO_SPLIT_LINES: 'LINES_ATTACH_TO_SPLIT_LINES',
    BRANCH_STATUS_MODIFICATION: 'BRANCH_STATUS_MODIFICATION',
    EQUIPMENT_ATTRIBUTE_MODIFICATION: 'EQUIPMENT_ATTRIBUTE_MODIFICATION',
    DELETE_VOLTAGE_LEVEL_ON_LINE: 'DELETE_VOLTAGE_LEVEL_ON_LINE',
    DELETE_ATTACHING_LINE: 'DELETE_ATTACHING_LINE',

});
export const equipments = Object.freeze({
    substations: 'substations',
    voltageLevels: 'voltageLevels',
    lines: 'lines',
    twoWindingsTransformers: 'twoWindingsTransformers',
    threeWindingsTransformers: 'threeWindingsTransformers',
    generators: 'generators',
    loads: 'loads',
    batteries: 'batteries',
    danglingLines: 'danglingLines',
    hvdcLines: 'hvdcLines',
    lccConverterStations: 'lccConverterStations',
    vscConverterStations: 'vscConverterStations',
    shuntCompensators: 'shuntCompensators',
    staticVarCompensators: 'staticVarCompensators',
});