export const MODIFICATION_TYPES = {
    GROOVY_SCRIPT: {
        type: 'GROOVY_SCRIPT',
    },
    LOAD_CREATION: {
        type: 'LOAD_CREATION',
    },
    LOAD_MODIFICATION: {
        type: 'LOAD_MODIFICATION',
    },
    GENERATOR_CREATION: {
        type: 'GENERATOR_CREATION',
    },
    GENERATOR_MODIFICATION: {
        type: 'GENERATOR_MODIFICATION',
    },
    LINE_CREATION: {
        type: 'LINE_CREATION',
    },
    SUBSTATION_CREATION: {
        type: 'SUBSTATION_CREATION',
    },
    VOLTAGE_LEVEL_CREATION: {
        type: 'VOLTAGE_LEVEL_CREATION',
    },
    SHUNT_COMPENSATOR_CREATION: {
        type: 'SHUNT_COMPENSATOR_CREATION',
    },
    TWO_WINDINGS_TRANSFORMER_CREATION: {
        type: 'TWO_WINDINGS_TRANSFORMER_CREATION',
    },
    EQUIPMENT_DELETION: {
        type: 'EQUIPMENT_DELETION',
    },
    LINE_SPLIT_WITH_VOLTAGE_LEVEL: {
        type: 'LINE_SPLIT_WITH_VOLTAGE_LEVEL',
    },
    LINE_ATTACH_TO_VOLTAGE_LEVEL: {
        type: 'LINE_ATTACH_TO_VOLTAGE_LEVEL',
    },
    LINES_ATTACH_TO_SPLIT_LINES: {
        type: 'LINES_ATTACH_TO_SPLIT_LINES',
    },
    BRANCH_STATUS_MODIFICATION: {
        type: 'BRANCH_STATUS_MODIFICATION',
    },
    EQUIPMENT_ATTRIBUTE_MODIFICATION: {
        type: 'EQUIPMENT_ATTRIBUTE_MODIFICATION',
    },
    LOAD_SCALING: {
        type: 'LOAD_SCALING',
    },
    DELETE_VOLTAGE_LEVEL_ON_LINE: {
        type: 'DELETE_VOLTAGE_LEVEL_ON_LINE',
    },
    DELETE_ATTACHING_LINE: {
        type: 'DELETE_ATTACHING_LINE',
    },
};
