/**
 * Copyright (c) 2023, RTE (http://www.rte-france.com)
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

export enum MODIFICATION_TYPE {
    GROOVY_SCRIPT = 'GROOVY_SCRIPT',
    LOAD_CREATION = 'LOAD_CREATION',
    LOAD_MODIFICATION = 'LOAD_MODIFICATION',
    BATTERY_CREATION = 'BATTERY_CREATION',
    BATTERY_MODIFICATION = 'BATTERY_MODIFICATION',
    GENERATOR_CREATION = 'GENERATOR_CREATION',
    GENERATOR_MODIFICATION = 'GENERATOR_MODIFICATION',
    LINE_CREATION = 'LINE_CREATION',
    LINE_MODIFICATION = 'LINE_MODIFICATION',
    SUBSTATION_CREATION = 'SUBSTATION_CREATION',
    SUBSTATION_MODIFICATION = 'SUBSTATION_MODIFICATION',
    VOLTAGE_LEVEL_CREATION = 'VOLTAGE_LEVEL_CREATION',
    VOLTAGE_LEVEL_MODIFICATION = 'VOLTAGE_LEVEL_MODIFICATION',
    SHUNT_COMPENSATOR_CREATION = 'SHUNT_COMPENSATOR_CREATION',
    SHUNT_COMPENSATOR_MODIFICATION = 'SHUNT_COMPENSATOR_MODIFICATION',
    STATIC_VAR_COMPENSATOR_CREATION = 'STATIC_VAR_COMPENSATOR_CREATION',
    TWO_WINDINGS_TRANSFORMER_CREATION = 'TWO_WINDINGS_TRANSFORMER_CREATION',
    TWO_WINDINGS_TRANSFORMER_MODIFICATION = 'TWO_WINDINGS_TRANSFORMER_MODIFICATION',
    VSC_CREATION = 'VSC_CREATION',
    EQUIPMENT_DELETION = 'EQUIPMENT_DELETION',
    BY_FILTER_DELETION = 'BY_FILTER_DELETION',
    LINE_SPLIT_WITH_VOLTAGE_LEVEL = 'LINE_SPLIT_WITH_VOLTAGE_LEVEL',
    LINE_ATTACH_TO_VOLTAGE_LEVEL = 'LINE_ATTACH_TO_VOLTAGE_LEVEL',
    LINES_ATTACH_TO_SPLIT_LINES = 'LINES_ATTACH_TO_SPLIT_LINES',
    OPERATING_STATUS_MODIFICATION = 'OPERATING_STATUS_MODIFICATION',
    EQUIPMENT_ATTRIBUTE_MODIFICATION = 'EQUIPMENT_ATTRIBUTE_MODIFICATION',
    LOAD_SCALING = 'LOAD_SCALING',
    DELETE_VOLTAGE_LEVEL_ON_LINE = 'DELETE_VOLTAGE_LEVEL_ON_LINE',
    DELETE_ATTACHING_LINE = 'DELETE_ATTACHING_LINE',
    GENERATOR_SCALING = 'GENERATOR_SCALING',
    GENERATION_DISPATCH = 'GENERATION_DISPATCH',
    VOLTAGE_INIT_MODIFICATION = 'VOLTAGE_INIT_MODIFICATION',
    CONVERTER_STATION_CREATION = 'CONVERTER_STATION_CREATION',
    TABULAR_MODIFICATION = 'TABULAR_MODIFICATION',
    BY_FORMULA_MODIFICATION = 'BY_FORMULA_MODIFICATION',
    TABULAR_CREATION = 'TABULAR_CREATION',
    VSC_MODIFICATION = 'VSC_MODIFICATION',
    CONVERTER_STATION_MODIFICATION = 'CONVERTER_STATION_MODIFICATION',
    COMPOSITE_MODIFICATION = 'COMPOSITE_MODIFICATION',
}

export const MODIFICATION_TYPES = {
    GROOVY_SCRIPT: {
        type: MODIFICATION_TYPE.GROOVY_SCRIPT,
    },
    LOAD_CREATION: {
        type: MODIFICATION_TYPE.LOAD_CREATION,
    },
    LOAD_MODIFICATION: {
        type: MODIFICATION_TYPE.LOAD_MODIFICATION,
    },
    BATTERY_CREATION: {
        type: MODIFICATION_TYPE.BATTERY_CREATION,
    },
    BATTERY_MODIFICATION: {
        type: MODIFICATION_TYPE.BATTERY_MODIFICATION,
    },
    GENERATOR_CREATION: {
        type: MODIFICATION_TYPE.GENERATOR_CREATION,
    },
    GENERATOR_MODIFICATION: {
        type: MODIFICATION_TYPE.GENERATOR_MODIFICATION,
    },
    LINE_CREATION: {
        type: MODIFICATION_TYPE.LINE_CREATION,
    },
    LINE_MODIFICATION: {
        type: MODIFICATION_TYPE.LINE_MODIFICATION,
    },
    SUBSTATION_CREATION: {
        type: MODIFICATION_TYPE.SUBSTATION_CREATION,
    },
    SUBSTATION_MODIFICATION: {
        type: MODIFICATION_TYPE.SUBSTATION_MODIFICATION,
    },
    VOLTAGE_LEVEL_CREATION: {
        type: MODIFICATION_TYPE.VOLTAGE_LEVEL_CREATION,
    },
    VOLTAGE_LEVEL_MODIFICATION: {
        type: MODIFICATION_TYPE.VOLTAGE_LEVEL_MODIFICATION,
    },
    SHUNT_COMPENSATOR_CREATION: {
        type: MODIFICATION_TYPE.SHUNT_COMPENSATOR_CREATION,
    },
    SHUNT_COMPENSATOR_MODIFICATION: {
        type: MODIFICATION_TYPE.SHUNT_COMPENSATOR_MODIFICATION,
    },
    STATIC_VAR_COMPENSATOR_CREATION: {
        type: MODIFICATION_TYPE.STATIC_VAR_COMPENSATOR_CREATION,
    },
    TWO_WINDINGS_TRANSFORMER_CREATION: {
        type: MODIFICATION_TYPE.TWO_WINDINGS_TRANSFORMER_CREATION,
    },
    TWO_WINDINGS_TRANSFORMER_MODIFICATION: {
        type: MODIFICATION_TYPE.TWO_WINDINGS_TRANSFORMER_MODIFICATION,
    },
    VSC_CREATION: {
        type: MODIFICATION_TYPE.VSC_CREATION,
    },
    EQUIPMENT_DELETION: {
        type: MODIFICATION_TYPE.EQUIPMENT_DELETION,
    },
    BY_FILTER_DELETION: {
        type: MODIFICATION_TYPE.BY_FILTER_DELETION,
    },
    LINE_SPLIT_WITH_VOLTAGE_LEVEL: {
        type: MODIFICATION_TYPE.LINE_SPLIT_WITH_VOLTAGE_LEVEL,
    },
    LINE_ATTACH_TO_VOLTAGE_LEVEL: {
        type: MODIFICATION_TYPE.LINE_ATTACH_TO_VOLTAGE_LEVEL,
    },
    LINES_ATTACH_TO_SPLIT_LINES: {
        type: MODIFICATION_TYPE.LINES_ATTACH_TO_SPLIT_LINES,
    },
    OPERATING_STATUS_MODIFICATION: {
        type: MODIFICATION_TYPE.OPERATING_STATUS_MODIFICATION,
    },
    EQUIPMENT_ATTRIBUTE_MODIFICATION: {
        type: MODIFICATION_TYPE.EQUIPMENT_ATTRIBUTE_MODIFICATION,
    },
    LOAD_SCALING: {
        type: MODIFICATION_TYPE.LOAD_SCALING,
    },
    DELETE_VOLTAGE_LEVEL_ON_LINE: {
        type: MODIFICATION_TYPE.DELETE_VOLTAGE_LEVEL_ON_LINE,
    },
    DELETE_ATTACHING_LINE: {
        type: MODIFICATION_TYPE.DELETE_ATTACHING_LINE,
    },
    GENERATOR_SCALING: {
        type: MODIFICATION_TYPE.GENERATOR_SCALING,
    },
    GENERATION_DISPATCH: {
        type: MODIFICATION_TYPE.GENERATION_DISPATCH,
    },
    VOLTAGE_INIT_MODIFICATION: {
        type: MODIFICATION_TYPE.VOLTAGE_INIT_MODIFICATION,
    },
    CONVERTER_STATION_CREATION: {
        type: MODIFICATION_TYPE.CONVERTER_STATION_CREATION,
    },
    TABULAR_MODIFICATION: {
        type: MODIFICATION_TYPE.TABULAR_MODIFICATION,
    },
    BY_FORMULA_MODIFICATION: {
        type: MODIFICATION_TYPE.BY_FORMULA_MODIFICATION,
    },
    TABULAR_CREATION: {
        type: MODIFICATION_TYPE.TABULAR_CREATION,
    },
    VSC_MODIFICATION: {
        type: MODIFICATION_TYPE.VSC_MODIFICATION,
    },
    CONVERTER_STATION_MODIFICATION: {
        type: MODIFICATION_TYPE.CONVERTER_STATION_MODIFICATION,
    },
    COMPOSITE_MODIFICATION: {
        type: MODIFICATION_TYPE.COMPOSITE_MODIFICATION,
    },
};
