name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/build-frontend-app-generic.yml@6ffe4abfca563a8b6dab7e993da2cc46cf9a15a9
    with:
      dockerImage: gridsuite/gridstudy-app
      dockerUsername: gridsuiteci
      eventType: gridstudy_app_updated
      licensercPath: .github/config/.licenserc.yaml
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
