name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: Release version (vX.X)
        required: true
      gitReference:
        description: SHA of the commit from where to release or branch name
        required: true

jobs:
  run-release:
    uses: powsybl/github-ci/.github/workflows/prepare-release.yml@f078f32800ad0555275dedb3e200f87ad1560a83
    with:
      githubappId: ${{ vars.GRIDSUITE_ACTIONS_APPID }}
      releaseVersion: ${{ github.event.inputs.releaseVersion }}
      gitReference: ${{ github.event.inputs.gitReference }}
    secrets:
      VERSIONBUMP_GHAPP_PRIVATE_KEY: ${{ secrets.VERSIONBUMP_GHAPP_PRIVATE_KEY }}
